# Generated by Django 5.1.2 on 2024-11-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(related_name='alumnosGrupo', to='sistema.alumno'),
        ),
    ]
