# Generated by Django 5.1.2 on 2024-11-22 10:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('usuarioescolar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('sistema.usuarioescolar',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='menu',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tutorAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tutorAlumno', to='sistema.tutor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupoProfesor', to='sistema.grupo'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrosAsistencia', to='sistema.alumno'),
        ),
        migrations.AlterField(
            model_name='registrocalificaciones',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacionesGrupo', to='sistema.grupo'),
        ),
        migrations.CreateModel(
            name='MenuPlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_platillos', to='sistema.menusemanal')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillo_menus', to='sistema.platillo')),
            ],
            options={
                'unique_together': {('menu', 'platillo', 'dia')},
            },
        ),
        migrations.AddField(
            model_name='menusemanal',
            name='platillos',
            field=models.ManyToManyField(related_name='menus', through='sistema.MenuPlatillo', to='sistema.platillo'),
        ),
        migrations.DeleteModel(
            name='ReporteAlumno',
        ),
    ]
