# Generated by Django 5.1.2 on 2024-10-29 03:44

import django.db.models.deletion
import sistema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDeActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horarios De Actividades',
            },
        ),
        migrations.AlterModelOptions(
            name='menusemanal',
            options={'verbose_name': 'Menú Semanal', 'verbose_name_plural': 'Menús Semanales'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaFinal',
            field=models.TimeField(verbose_name='12:00'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaInicio',
            field=models.TimeField(verbose_name='06:00'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default='Actividad Sin Nombre', max_length=200),
        ),
        migrations.AddField(
            model_name='actividad',
            name='horario',
            field=models.ForeignKey(default=sistema.models.HorarioDeActividades.obtenerHorarioPorDefecto, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='sistema.horariodeactividades'),
        ),
    ]
