# Generated by Django 5.1.2 on 2024-11-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_tutoralumno_alumno_tutoralumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='consideracionesMenu',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
