# Generated by Django 5.1.2 on 2024-10-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_horariodeactividades_alter_menusemanal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horaFinal',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaInicio',
            field=models.TimeField(),
        ),
    ]
