# Generated by Django 5.1.2 on 2024-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_actividad_options_alter_usuarioescolar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(related_name='alumnosGrupo', to='sistema.alumno'),
        ),
    ]
