# Generated by Django 5.1.2 on 2024-10-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_actividad_horafinal_alter_actividad_horainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='sistema.horariodeactividades'),
        ),
    ]
