# Generated by Django 5.1.2 on 2024-11-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_grupo_alumnos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificacion'},
        ),
    ]
