# Generated by Django 5.1.3 on 2024-11-18 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_notificacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('consideraciones', models.TextField(blank=True, null=True)),
                ('dia', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], help_text='Día de la semana al que pertenece este platillo.', max_length=10, null=True)),
                ('menu', models.ForeignKey(blank=True, help_text='Menú al que pertenece este platillo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platillos', to='sistema.menusemanal')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Plato',
        ),
    ]
