# Generated by Django 5.1.2 on 2024-10-29 05:03

import django.db.models.deletion
import sistema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_actividad_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horario',
            field=models.ForeignKey(default=sistema.models.HorarioDeActividades.obtenerHorarioPorDefecto, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='sistema.horariodeactividades'),
        ),
    ]
