# Generated by Django 5.1.2 on 2024-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_horariodeactividades_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodeactividades',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
